import io
import requests
import streamlit as st

st.set_page_config(page_title="DreamCraft AI", page_icon="🎨")

st.title("🎨 DreamCraft AI")
st.write("Generate breathtaking images instantly using AI")

prompt = st.text_area("Describe your vision...", placeholder="A cybernetic samurai in neon rain...")

API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
HEADERS = {"Authorization": "Bearer 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"}

def generate_image(payload):
    response = requests.post(API_URL, headers=HEADERS, json=payload)
    return response.content

if st.button("GENERATE MAGIC"):
    if prompt.strip() == "":
        st.warning("Please enter a prompt first!")
    else:
        with st.spinner("Creating your masterpiece..."):
            image_bytes = generate_image({"inputs": prompt})
            try:
                from PIL import Image
                image = Image.open(io.BytesIO(image_bytes))
                st.image(image, caption="Generated by DreamCraft AI", use_container_width=True)
            except Exception:
                st.error("Error generating image. Please check your token or prompt.")
                
